### PR TITLE
take 3 to 4 sec less time during inference

### PR DESCRIPTION
**Pull request by Akshaysharma29**
Hi team, I like tapas work and like to contribute. So in this push, I have optimized the code for the WTQ task. and it will take 3 to 4 sec lesser time. I have verified this on colab. Hope you like my contribution.
Thanks.

### CODE REVIEW

**Comment by Akshaysharma29** [comment]
@googlebot I signed it!

**Comment by eisenjulian** [comment]
Thanks for the interest and contribution. The reason for this overhead time is that there we are creating an empty dev file for demo purposes in the colab, which doesn't happen when the script is used normally and both the dev and test set exists. The proposed solution would break that use-case. 

An application with only one set for prediction should call `_predict_for_set`once instead of twice. If you are interested, you can modify your PR so that the `_predict` method checks for the existence of the dev file and skips it if is missing, then colab can also skip creating the empty file.

Let me know if this makes sense

**Review by eisenjulian — CHANGES_REQUESTED** [review]
Thanks for the interest and contribution. The reason for this overhead time is that there we are creating an empty dev file for demo purposes in the colab, which doesn't happen when the script is used normally and both the dev and test set exists. The proposed solution would break that use-case.

An application with only one set for prediction should call _predict_for_setonce instead of twice. If you are interested, you can modify your PR so that the _predict method checks for the existence of the dev file and skips it if is missing, then colab can also skip creating the empty file.

Let me know if this makes sense

**Comment by Akshaysharma29** [comment]
Hi, @eisenjulian yes I have not looked that it will break the use case of predicting on dev.
Thanks for your words. I will create a new PR with your suggestions.

**Pull request closed without merging**
