### PR TITLE
Add huggingface/transformers mention to the README

### PR DESCRIPTION
**Pull request by LysandreJik**
As seen with @thomasmueller-google, this PR adds a mention of the huggingface/transformers implementation. It adds a direct link to the model hub where users can play with TAPAS directly and experience its table question answering capabilities.

### CODE REVIEW

**Comment by LysandreJik** [comment]
@googlebot I signed it!

**Comment by LysandreJik** [comment]
Thank you @thomasmueller-google!

**Review by theBolck — COMMENTED** [review]
README.md

**Comment by theBolck** [comment]
README.md

**Pull request merged**
